arithmetic/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('exercise/', views.exercise, name='exercise'),
    path('rule<int:pk>/', views.rule_detail, name='rule_detail'),
    path('rules/', views.rules, name='rules'),
    path('student<int:pk>/', views.student_detail, name='student_detail'),
    path('students/', views.students, name='students'),
    path('arithmetic/', views.arithmetic, name='arithmetic'),
    path('formulas/<int:pk>/r=<int:pre_right>/t=<int:pre_total>/g=<int:grade>', views.formulas, name='formulas'),
    path('test/',views.formulas_forms,name='formulas_forms')
#    path('filtered/', views.rules_filtered, name='rules_filtered'),
]

infaculty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('arithmetic.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

arithmetic/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager

# Create your models here.

class Subject(models.Model):
    def __str__(self):
        return self.subject_name

    subject_name = models.CharField(max_length=50)

class Year(models.Model):
    def __str__(self):
        return(str(self.year_number))

    year_number = models.IntegerField()

class Rule(models.Model):
    def __str__(self):
        return self.rule_name
    rule_name = models.CharField(max_length=50)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    tags = TaggableManager()

class Block(models.Model):
    def __str__(self):
        return self.block_text
    rule=models.ForeignKey(Rule, on_delete=models.CASCADE)
    block_text=models.TextField()
    block_image=models.ImageField(blank=True)

class Student(models.Model):
    def __str__(self):
        return self.student_name
    #Student_Age=models.IntegerField()
    student_name=models.CharField(max_length=50)
    #Lasr_Name=models.CharField(max_length=50)
    #Schedule=models.
    #Scores =
    rules_set = models.ManyToManyField(Rule)

class QuestionWithSelection(models.Model):
    def __str__(self):
        return self.QWS_name
    QWS_name = models.CharField(max_length=50)
    QWS_text = models.CharField(max_length=150)
    QWS_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    QWS_year = models.ForeignKey(Year, on_delete=models.CASCADE)


class Selection(models.Model):
    def __str__(self):
        return self.selection_text
    question = models.ForeignKey(QuestionWithSelection, on_delete = models.CASCADE)
    selection_text=models.CharField(max_length=150)
    selection_correct = models.BooleanField()
    #selection_image=models.ImageField(blank=True)

arithmetic/views.py
from django.shortcuts import render, get_object_or_404
from random import randint, choice
from django.http import HttpResponse
from .models import Rule, Student, QuestionWithSelection, Subject
# Create your views here.

def index(request):
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/index.html',{'subjects':subjects})

def formulas(request, pk, pre_right = 0, pre_total = 0, grade = 11):
    QWS = QuestionWithSelection.objects.filter(QWS_subject=pk, QWS_year__year_number__lte=grade).order_by('?').first()
    if QWS:
        QWStext = QWS.QWS_text
        QWSans  = QWS.selection_set.all().order_by('?')
    else:
        QWStext = 'Нет вопросов по таким критериям'
        QWSans = None
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/equations.html',{'QWStext':QWStext,'QWSans':QWSans, 'subjects':subjects,'pre_right':pre_right,'pre_total':pre_total,'subject':pk,'grade':grade})


def formulas_forms(request):
    try:
        QWS = QuestionWithSelection.objects.order_by('?').first()
    except Exception:
        QWS = None
    QWStext = QWS.QWS_text
    QWSans  = QWS.selection_set.all().order_by('?')
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/formulas.html',{'QWStext':QWStext,'QWSans':QWSans, 'subjects':subjects})


def arithmetic(request):
    left=randint(10,40)
    right=randint(2,10)
    sign=choice(['+','*','-','/'])
    if sign=='*':
        answer=left*right
    elif sign=='+':
        answer=left+right
    elif sign=='-':
        answer=left-right
    elif sign=='/':
        while left%right!=0:
            left=randint(10,40)
            right=randint(2,10)
        answer=left//right

    #return HttpResponse(str(left)+'*'+str(right))
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/arithmetic.html',{'left':left,'right':right,'answer':answer,'sign':sign, 'subjects':subjects})

def exercise(request):
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/exercise.html',{'subjects':subjects})

def rule_detail(request, pk):
    rule = get_object_or_404(Rule, pk=pk)
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/rule_detail.html',{'rule':rule, 'subjects':subjects})

def rules(request,pk=None):
    rules = Rule.objects.all()
    if pk:
        rules = Rule.objects.filter(tags__name__in=[str(pk)])
    alltags=[]
    for rule in rules:
        for tag in rule.tags.all():
            if tag not in alltags:
                alltags.append(tag)
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/rules.html',{'rules':rules,'alltags':alltags, 'subjects':subjects})
'''
def rules_filtered(request,t):
    rules = Rule.objects.filter(tags__name__in=[str(t)])
    alltags=[]
    for rule in rules:
        for tag in rule.tags.all():
            if tag not in alltags:
                alltags.append(tag)
    return render(request, 'arithmetic/rules.html',{'rules':rules,'alltags':alltags})
'''

def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/student_detail.html',{'student':student, 'subjects':subjects})

def students(request):
    students = Student.objects.all()
    subjects = Subject.objects.all()
    return render(request, 'arithmetic/students.html',{'students':students, 'subjects':subjects})

arithmetic/templates/arithmetic/arithmetic.html
{%extends 'arithmetic/base.html'%}

{%block content%}

<div class="arithmetic">
{{left}}{{sign}}{{right}}=?
</div>

<div class="button">

</div>

<div class="answer">
  <input type="text" id="test">
  <div class="answer_button">
    <input type="button" id="testbutton" value="Проверить" onclick="z()" class="equations_button"><span id="err"></span>
  </div>


<script>
function z()
{

var a=document.getElementById("test");
var b=document.getElementById("testbutton");



  if(a.value=={{answer}})
  {
    document.location.reload(true)
  }
  else
  {
    document.getElementById('err').innerHTML= '  <font color="red"> &#10008 </font>  ';
  }






}
</script>
</div>
{%endblock%}

arithmetic/templates/arithmetic/base.html
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{% static '/css/arithmetic.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Poiret+One&display=swap" rel="stylesheet">
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<title>Независимый Факультет</title>
</head>
<body>
  <body style="background: #ffffff">
<div id="container">



<div class="top_menu">
  <ul class="topmenu">
  <li><a class="top_menu_button">Упражнения<i class="fa fa-angle-down"></i></a>
    <ul class="submenu">
      {% for subject in subjects%}
      <div class="article">
        <li><a href="{% url 'formulas' pk=subject.pk pre_right=0 pre_total=0 grade=11%}">{{subject.subject_name}}</a></li>
      </div>
      {%endfor%}
    </ul>
  </li>
  <li><a href='/rules/' class="top_menu_button">Правила</a><li>
  <li><a href="/students/" class="top_menu_button">Учащиеся</a><li>
  </ul>
</div>

<div class="header">
  <div class="progress-container">
    <div class="progress-bar" id="myBar"></div>
  </div>
</div>

<div id="content">

      {%block content%}
      {%endblock%}

</div>


<div id="foot">

    <a onclick="goBack()"> <span class="glyphicon glyphicon-thumbs-down red"></span></a>
<script>
  function goBack() {
    window.history.back()
  }
</script>

<script>
window.onscroll = function() {myFunction()};

function myFunction() {
var winScroll = document.body.scrollTop || document.documentElement.scrollTop;
var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
var scrolled = (winScroll / height) * 100;
document.getElementById("myBar").style.width = scrolled + "%";
}
</script>

</div>
</div>
  </body>
</html>

arithmetic/templates/arithmetic/equations.html
{%extends 'arithmetic/base.html'%}

{%block content%}

<script>
window.onload = function class_select(){
  if ({{grade}}==5){
    document.getElementById("vkl1").checked=true;
  }
  if ({{grade}}==6){
    document.getElementById("vkl2").checked=true;
  }
  if ({{grade}}==7){
    document.getElementById("vkl3").checked=true;
  }
  if ({{grade}}==8){
    document.getElementById("vkl4").checked=true;
  }
  if ({{grade}}==9){
    document.getElementById("vkl5").checked=true;
  }
  if ({{grade}}==10){
    document.getElementById("vkl6").checked=true;
  }
  if ({{grade}}==11){
    document.getElementById("vkl7").checked=true;
  }
}

</script>

<div class="korpus">

  <input type="radio" name="odin" id="vkl1" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=5%}'" /><label for="vkl1">5</label>
  <input type="radio" name="odin" id="vkl2" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=6%}'" /><label for="vkl2">6</label>
  <input type="radio" name="odin" id="vkl3" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=7%}'" /><label for="vkl3">7</label>
  <input type="radio" name="odin" id="vkl4" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=8%}'" /><label for="vkl4">8</label>
  <input type="radio" name="odin" id="vkl5" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=9%}'" /><label for="vkl5">9</label>
  <input type="radio" name="odin" id="vkl6" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=10%}'" /><label for="vkl6">10</label>
  <input type="radio" name="odin" id="vkl7" onclick="window.location.href='{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total grade=11%}'" /><label for="vkl7">11</label>

</div>

<div class="equations_question">
  <p>{{QWStext}}</p>
</div>

<div class="selection_button">
  <div class="equations_selection">
    {%for selection in QWSans%}
    <input type="radio" id="{{selection.id}}" name="answer" value="{{selection.selection_correct}}"> <label for="{{selection.id}}">{{selection.selection_text}}</label><br>
    {%endfor%}
  </div>

  <div>
    <button onclick="check()" class="equations_button">Выбрать</button>

    <span id="log"> </span>
    <script>
      var jright = {{pre_right}};
      var jtotal = {{pre_total}}+1;
      function check(){
        if (document.querySelector('input[name=answer]:checked').value=="False")
        {
          document.getElementById('log').innerHTML=' <font color="red"> &#10008 </font> ';
          document.location.href = "{% url 'formulas' pk=subject pre_right=pre_right pre_total=pre_total|add:"1" grade=grade%}";
        }
        else
        {
          document.location.href = "{% url 'formulas' pk=subject pre_right=pre_right|add:"1" pre_total=pre_total grade=grade%}";
        }
      }
    </script>
  </div>
</div>

<div class="checkmark_cross">
<p>Всего верных {{pre_right}} из {{pre_total|add:pre_right}}</p>

  {%with ''|center:pre_right as range%}
  <div class="checkmark">
  {% for cross in range%}

  <span style="color:#00aa00">&#10004</span>

  {%endfor%}
  </div>
  {%endwith%}


<div class="cross">
  {%with ''|center:pre_total as range%}
  {% for cross in range%}

  <span style="color:#dd0000">&#10008</span>

  {%endfor%}
  {%endwith%}
</div>
</div>

{%endblock%}

arithmetic/templates/arithmetic/exercise.html
{%extends 'arithmetic/base.html'%}

{%block content%}
<div class="exercise">
  <a href='/arithmetic/'>Арифметика</a>
  <a href="/formulas/">Уравнения</a>
</div>


{%endblock%}

arithmetic/templates/arithmetic/formulas.html
{%extends 'arithmetic/base.html'%}

{%block content%}
<div class="equations_question">
  <p>{{QWStext}}</p>
</div>

<form method="get">


<div class="selection_button">
  <div class="equations_selection">
    {%for selection in QWSans%}
    <input type="radio" id="{{selection.id}}" name="answer" value="{{selection.selection_correct}}"> <label for="{{selection.id}}">{{selection.selection_text}}</label><br>
    {%endfor%}
  </div>

  <div>
    <button onclick="check()" class="equations_button">Выбрать</button>

    <span id="log"> </span>
    <script>
      function check(){
        if (document.querySelector('input[name=answer]:checked').value=="False")
        {
          document.getElementById('log').innerHTML=' <font color="red"> &#10008 </font> ';
        }
        else
        {
          document.location.reload(true);
        }
      }
    </script>
  </div>
</div>
</form>
{%endblock%}

arithmetic/templates/arithmetic/index.html
{%extends 'arithmetic/base.html'%}

{%block content%}
<h1> Независимый Факультет</h1>

Это сайт с упражнениями для учеников Независимого Факультета.
Перейдите к вкладке "Упражнения" и выберите нужную тему. Для повторения правил перейдите к соответствующему разделу


{%endblock%}

arithmetic/templates/arithmetic/rule_detail.html
{%extends 'arithmetic/base.html'%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"></script>
<!-- MathJax configuration -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"] ],
        displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
        processEscapes: true,
        processEnvironments: true
    },
    // Center justify equations in code and markdown cells. Elsewhere
    // we use CSS to left justify single line equations in code cells.
    displayAlign: 'center',
    "HTML-CSS": {
        styles: {'.MathJax_Display': {"margin": 0}},
        linebreaks: { automatic: true }
    }
});
</script>
{%block content%}
<div class="rule_detail">
  {% for block in rule.block_set.all %}
  {{block.block_text|linebreaksbr}}
  {% if block.block_image %}
  <center><img src= "{{MEDIA_URL}}{{block.block_image}}" alt="Image" width="40%" justify="center"></center>
  {% endif %}

  {% endfor %}
</div>


{%endblock%}

arithmetic/templates/arithmetic/rules.html
{%extends 'arithmetic/base.html'%}


{%block content%}

{%for tag in alltags%}

{%endfor%}
<div class="rule">

  <div class="rule_name">
    {% for rule in rules%}
    <p><a href="{% url 'rule_detail' pk=rule.pk %}">{{rule.rule_name}}</a></p>

    <div class="rule_tags">
      {%for tag in rule.tags.names%}
      <small>{{tag}}</small>
      {%endfor%}
    </div>




    {%endfor%}
  </div>
</div>

{%endblock%}

arithmetic/templates/arithmetic/student_detail.html
{%extends 'arithmetic/base.html'%}

{%block content%}
<div class="student_detail">

  <div class="student_detail_name">
    {{student.student_name|linebreaksbr}}
  </div>

  {% for rule in student.rules_set.all %}
  <a href="{% url 'rule_detail' pk=rule.pk %}">{{rule.rule_name}}</a>
  {%endfor%}

</div>

{%endblock%}

arithmetic/templates/arithmetic/students.html
{%extends 'arithmetic/base.html'%}


{%block content%}

<div class="students">
  {% for student in students%}
    <p><a href="{% url 'student_detail' pk=student.pk %}">{{student.student_name}}</a></p>
  {%endfor%}

</div>


{%endblock%}